black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 254
  - 90
  min:
  - 0
  - 120
  - 0
green:
  max:
  - 255
  - 120
  - 180
  min:
  - 0
  - 0
  - 100
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 160
  - 135
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
